### PR TITLE
Fix comments in queries causing bad results

### PR DESCRIPTION
**Pull request by LinuxJedi**
ColumnStore modifies the query string stored in the thd object so
that it can be used by ColumnStore's parser. The biggest operation
here is to remove newline characters. This doesn't remove inline
comments before removing the newline characters so an inline
comment turns the rest of the query into a comment when the
newline characters are dropped.

The effect of this can be seen when ColumnStore creates an aria
temporary table, it builds a query to do this using the processed
version of the current query.

This commit removes the SQL comments during the query text
processing.

### CODE REVIEW

**Comment by ernstae** [comment]
This would be supremely helpful for our installation and testing at IHME.

**Comment by LinuxJedi** [comment]
this fix will be merged before the next release. Unfortunately it was too late for the 1.0.2 freeze.

**Comment by ernstae** [comment]
This does represent a blocking issue for the product for which we're targeting ColumnStore (unless our devs drop all the embedded queries in our SQL -- so getting an idea of targeted release date for 1.0.3 would be helpful for us.

**Comment by ghost** [comment]
Hey Andrew Ernst, we just released 1.0.2 and as mentioned, it didn't have the fix for this issue MCOL-256 in it. But we do have a fix and we can do a point release with it and provide it to you to test with. It would be 1.0.2.1-1. We are looking into that now, if you would be interested in taking point release with just that fix. We would build it and run it through our regression test suites.
If you are interested, let me know what OS you are running on and the type of packages you install, like rpm or binaries.

David Hill

**Comment by ernstae** [comment]
@davidhilldallas - We're doing our testing on Centos 7 (there wasn't a Ubuntu 14.04 debian package -- which is our institutional standard for database servers, and we haven't validated 16.04 yet, because of FusionIO drivers not compiling properly on the 4.2+ kernel versions)

So, to answer your question - a point release with that fix would be very welcome for us, on Centos 7 as RPMs, which has been our standard installation method with ColumnStore, thus far.

Thanks!

**Comment by ghost** [comment]
great, we are generating a build for you to try out and I can provide to you a Centos 7 rpms package set.
That package should be available tomorrow once its built and we run it through our regression test cycle and QA testing for this issue.

David Hill

**Pull request merged**
